//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asv.Drones.Gui.Plugin.Weather {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RS() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Asv.Drones.Gui.Plugin.Weather.RS", typeof(RS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection error occurred.
        /// </summary>
        public static string WeatherProvider_ConnectionErrorMessage {
            get {
                return ResourceManager.GetString("WeatherProvider_ConnectionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0} - {1}.
        /// </summary>
        public static string WeatherProvider_CustomErrorMessage {
            get {
                return ResourceManager.GetString("WeatherProvider_CustomErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can change weather settings.
        /// </summary>
        public static string WeatherSettingsView_Description {
            get {
                return ResourceManager.GetString("WeatherSettingsView_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather settings.
        /// </summary>
        public static string WeatherSettingsView_Header {
            get {
                return ResourceManager.GetString("WeatherSettingsView_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you need enter your API key.
        /// </summary>
        public static string WeatherSettingsView_WeatherApiKey_Description {
            get {
                return ResourceManager.GetString("WeatherSettingsView_WeatherApiKey_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API key.
        /// </summary>
        public static string WeatherSettingsView_WeatherApiKey_Header {
            get {
                return ResourceManager.GetString("WeatherSettingsView_WeatherApiKey_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can choose weather provider.
        /// </summary>
        public static string WeatherSettingsView_WeatherProvider_Description {
            get {
                return ResourceManager.GetString("WeatherSettingsView_WeatherProvider_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather provider.
        /// </summary>
        public static string WeatherSettingsView_WeatherProvider_Header {
            get {
                return ResourceManager.GetString("WeatherSettingsView_WeatherProvider_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        public static string WeatherSettingsView_WeatherSwitch_Button_Hide {
            get {
                return ResourceManager.GetString("WeatherSettingsView_WeatherSwitch_Button_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string WeatherSettingsView_WeatherSwitch_Button_Show {
            get {
                return ResourceManager.GetString("WeatherSettingsView_WeatherSwitch_Button_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can change weather visibility on a flight page.
        /// </summary>
        public static string WeatherSettingsView_WeatherSwitch_Description {
            get {
                return ResourceManager.GetString("WeatherSettingsView_WeatherSwitch_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather visibility.
        /// </summary>
        public static string WeatherSettingsView_WeatherSwitch_Header {
            get {
                return ResourceManager.GetString("WeatherSettingsView_WeatherSwitch_Header", resourceCulture);
            }
        }
    }
}
